// <auto-generated />
namespace Prsctical_8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StudentFirstDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentFirstDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202311300446213_StudentFirstDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
